version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    depends_on:
      - redis 
      - postgres
      - cron
      - preset-data
    environment:
      DB_HOST: postgres
      DB_USER: c.huang
      DB_NAME: hahow_project_dev
      DB_PASSWORD: hahow_project
      CACHE_HOST: redis
      CACHE_PORT: 6379
  cron:
    build:
      context: .
      dockerfile: Dockerfile.cron
    ports:
      - "3001:3001"
    depends_on:
      - postgres
      - redis
    environment:
      DB_HOST: postgres
      DB_USER: c.huang
      DB_NAME: hahow_project_dev
      DB_PASSWORD: hahow_project
      CACHE_HOST: redis
      CACHE_PORT: 6379      
  preset-data:
    build:
      context: .
      dockerfile: Dockerfile.data
    ports:
      - "3002:3002"
    depends_on:
      - postgres
    environment:
      DB_HOST: postgres
      DB_USER: c.huang
      DB_NAME: hahow_project_dev
      DB_PASSWORD: hahow_project
      CACHE_HOST: redis
      CACHE_PORT: 6379      
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: hahow_project_dev
      POSTGRES_USER: c.huang
      POSTGRES_PASSWORD: hahow_project
    ports:
      - "5432:5432"
    volumes:
      - database:/data/db
  redis:
    image: redis:latest
volumes:
  database: