@startuml

entity User {
    * id
    name
    encrypted_password
    salt
}

entity Hero {
    * id
    name : str
    image : str
}

entity Profile {
    * id
    str : int
    int : int
    agi : int
    luk : int
}


Hero ||--|| Profile


@enduml
